Repository Ctrlpanel-gg/panel, pull requests merged in 2023-01, with the labels that each got.

#629 [FEATURE] Extension Support & Payment Gateways as Extensions 🔥
  app/Events/PaymentEvent.php
  app/Extensions/PaymentGateways/PayPal/index.php
  app/Extensions/PaymentGateways/PayPal/web_routes.php
  app/Extensions/PaymentGateways/Stripe/index.php
  app/Extensions/PaymentGateways/Stripe/web_routes.php
  app/Helpers/ExtensionHelper.php
  app/Http/Controllers/Admin/PaymentController.php
  app/Listeners/CreateInvoice.php
  app/Listeners/UserPayment.php
  app/Models/Payment.php
  app/Providers/EventServiceProvider.php
  app/Traits/Invoiceable.php
  public/images/Extensions/PaymentGateways/paypal_logo.png
  public/images/Extensions/PaymentGateways/stripe_logo.png
  routes/api.php
  routes/extensions_api.php
  routes/extensions_web.php
  routes/web.php
  themes/default/views/store/checkout.blade.php
Labels: feature, High Priority, PR-Open

#640 [Fix/Features] CSRF Ignoring Routes support & Fix Invoice creation on webhook
  app/Extensions/PaymentGateways/PayPal/config.php
  app/Extensions/PaymentGateways/PayPal/index.php
  app/Extensions/PaymentGateways/Stripe/config.php
  app/Extensions/PaymentGateways/Stripe/index.php
  app/Helpers/ExtensionHelper.php
  app/Http/Controllers/Admin/PaymentController.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Listeners/CreateInvoice.php
  app/Models/PartnerDiscount.php
  app/Traits/Invoiceable.php
Labels: feature, fix

#646 [Feature] Adding billing cycle system
  app/Console/Commands/ChargeServers.php
  app/Console/Kernel.php
  app/Extensions/PaymentGateways/PayPal/config.php
  app/Extensions/PaymentGateways/PayPal/index.php
  app/Extensions/PaymentGateways/Stripe/config.php
  app/Extensions/PaymentGateways/Stripe/index.php
  app/Helpers/ExtensionHelper.php
  app/Http/Controllers/Admin/PaymentController.php
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Controllers/Admin/ServerController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/ServerController.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Listeners/CreateInvoice.php
  app/Models/PartnerDiscount.php
  app/Models/Product.php
  app/Models/Server.php
  app/Models/User.php
  app/Traits/Invoiceable.php
  database/migrations/2022_06_16_092704_add_billing_period_to_products.php
  database/migrations/2022_06_16_094402_update_user_credits_datatype.php
  database/migrations/2022_06_16_095818_add_last_billed_field_to_servers.php
  database/migrations/2022_07_21_234527_add_cancelation_to_servers_table.php
  database/migrations/2022_07_21_234818_undo_decimal_in_price.php
  database/seeders/Seeds/ProductSeeder.php
  lang/bg.json
  lang/bs.json
  lang/cs.json
  lang/de.json
  lang/en.json
  lang/es.json
  lang/fr.json
  lang/he.json
  lang/hi.json
  lang/hu.json
  lang/it.json
  lang/nl.json
  lang/pl.json
  lang/pt.json
  lang/ro.json
  lang/ru.json
  lang/sh.json
  lang/sk.json
  lang/sr.json
  lang/sv.json
  lang/tr.json
  lang/zh.json
  routes/web.php
  themes/default/views/admin/products/create.blade.php
  themes/default/views/admin/products/edit.blade.php
  themes/default/views/admin/products/index.blade.php
  themes/default/views/admin/settings/tabs/system.blade.php
  themes/default/views/servers/create.blade.php
  themes/default/views/servers/index.blade.php
  themes/default/views/servers/settings.blade.php
Labels: feature, v0.10

#648 [Fix] User creation settings
  app/Classes/Settings/System.php
  database/seeders/Seeds/SettingsSeeder.php
  package-lock.json
  package.json
  themes/default/views/admin/settings/tabs/system.blade.php
  themes/default/views/layouts/app.blade.php
  themes/default/views/layouts/main.blade.php
  webpack.mix.js
Labels: Update needed
