Repository Ctrlpanel-gg/panel, pull requests merged in 2024-08, with the labels that each got.

#984 [Feature] Discord role on purchase
  app/Http/Controllers/Admin/ServerController.php
  app/Http/Controllers/Auth/SocialiteController.php
  app/Http/Controllers/ServerController.php
  app/Models/DiscordUser.php
  app/Settings/DiscordSettings.php
  database/settings/2024_06_25_133205_add_discord_settings.php
Labels: Feature, Medium Priority

#987 Fixed the problem with ticket middleware
  composer.lock
  routes/web.php
Labels: Bug / Fix, High Priority

#994 style: Improved Installer appearance
  public/installer/styles.css
  public/installer/views/admin-creation.php
  public/installer/views/dashboard-configuration.php
  public/installer/views/database-configuration.php
  public/installer/views/database-migration.php
  public/installer/views/email-configuration.php
  public/installer/views/layout-bottom.php
  public/installer/views/layout-top.php
  public/installer/views/mandatory-checks.php
  public/installer/views/pterodactyl-configuration.php
  public/installer/views/redis-configuration.php
  public/installer/views/timezone-configuration.php
Labels: Bug / Fix, Low Priority
