Repository Ctrlpanel-gg/panel, pull requests merged in 2024-07, with the labels that each got.

#951 fix: Panel Installer
  .gitignore
  app/Console/Commands/GetSettingCommand.php
  app/Console/Commands/SetSettingCommand.php
  app/Http/Kernel.php
  app/Http/Middleware/InstallerLock.php
  composer.json
  public/install/forms.php
  public/install/functions.php
  public/install/index.php
Labels: Bug / Fix, Feature, High Priority, Help Wanted

#972 refactor: installer
  .env.example
  app/Http/Middleware/InstallerLock.php
  app/Settings/TicketSettings.php
  public/install/forms.php
  public/install/functions.php
  public/install/index.php
  public/install/styles.css
  public/installer/dotenv.php
  public/installer/index.php
  public/installer/src/forms/admin.php
  public/installer/src/forms/dashboard.php
  public/installer/src/forms/database.php
  public/installer/src/forms/pterodactyl.php
  public/installer/src/forms/redis.php
  public/installer/src/forms/smtp.php
  public/installer/src/forms/timezone.php
  public/installer/src/functions/environment.php
  public/installer/src/functions/installer.php
  public/installer/src/functions/logging.php
  public/installer/src/functions/shell.php
  public/installer/src/functions/utils.php
  public/installer/src/phpmailer/Exception.php
  public/installer/src/phpmailer/PHPMailer.php
  public/installer/src/phpmailer/SMTP.php
  public/installer/styles.css
  public/installer/tailwind.config.js
  public/installer/tailwind_styles.css
  public/installer/views/admin-creation.php
  public/installer/views/dashboard-configuration.php
  public/installer/views/database-configuration.php
  public/installer/views/database-migration.php
  public/installer/views/email-configuration.php
  public/installer/views/installation-complete.php
  public/installer/views/layout-bottom.php
  public/installer/views/layout-top.php
  public/installer/views/mandatory-checks.php
  public/installer/views/pterodactyl-configuration.php
  public/installer/views/redis-configuration.php
  public/installer/views/timezone-configuration.php
Labels: Bug / Fix, Feature, Medium Priority

#926 feat: Mercadopago Integration
  app/Extensions/PaymentGateways/MercadoPago/MercadoPagoExtension.php
  app/Extensions/PaymentGateways/MercadoPago/MercadoPagoSettings.php
  app/Extensions/PaymentGateways/MercadoPago/migrations/2024_01_24_120635_create_mercadopago_settings.php
  app/Extensions/PaymentGateways/MercadoPago/web_routes.php
  config/permissions_web.php
  lang/en.json
  public/images/Extensions/PaymentGateways/mercadopago_logo.png
  themes/BlueInfinity/views/layouts/main.blade.php
  themes/default/views/layouts/main.blade.php
Labels: Feature, Low Priority, Payment Gateway

#981 fix: Panel installer
  public/installer/src/forms/admin.php
  public/installer/src/forms/database.php
  public/installer/src/forms/redis.php
  public/installer/src/forms/smtp.php
  public/installer/src/functions/logging.php
  public/installer/src/functions/utils.php
Labels: Bug / Fix, Feature, Medium Priority

#983 Fixed the problem with permissions and roles
  app/Http/Controllers/Admin/RoleController.php
  app/Http/Controllers/Admin/UserController.php
  app/Http/Controllers/Api/RoleController.php
  app/Http/Controllers/Api/UserController.php
  config/permissions_web.php
  database/migrations/2024_07_25_083712_update_settings_default_and_unique.php
  themes/default/views/admin/roles/edit.blade.php
  themes/default/views/admin/roles/index.blade.php
Labels: Bug / Fix, High Priority
